language: go
go:
  - tip
before_install:
  - go get -v github.com/mitchellh/gox
  - go get -v github.com/tcnksm/ghr
after_success:
  - gox -os="linux darwin windows" -arch="386 amd64" -output "pkg/{{.Dir}}_{{.OS}}_{{.Arch}}" -ldflags="-X main.Version=`git describe --tags`"
  - ghr --username uetchy --replace --prerelease pre-release pkg/
