language: go
go:
  - tip
before_install:
  - go get -v github.com/mitchellh/gox
  - go get -v github.com/tcnksm/ghr
after_success:
  - gox -os="linux darwin windows" -arch="386 amd64" -output "pkg/{{.Dir}}_{{.OS}}_{{.Arch}}" -ldflags="-X main.Version=`git describe --tags --match 'v*'`"
  - ghr --username uetchy --replace --delete --prerelease pre-release pkg/
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: "pkg/*"
  skip_cleanup: true
  on:
    tags: true
